
version: '3'

networks:
  default:
    external:
        name: wmnet

services:
  ppp:
    image: php:7.1.10-fpm
    container_name: land-php
    volumes:
      - ./:/usr/share/nginx/html/
    restart: always


  ngx:
    image: nginx:alpine
    container_name: land
    ports:
      - "0.0.0.0:27102:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html/
    depends_on:
      - ppp
    restart: always

#docker run -v /data/dc/nginx/conf.d/:/etc/nginx/conf.d -v /data/www:/usr/share/nginx/html/ -p80:80 -p81:81 -p28080:80 -p28081:81 -p443:443 --restart=always nginx:1.14.0

